version: "3"

services:
  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:latest
    container_name: mautrix-telegram
    restart: unless-stopped

    volumes:
      - ./data:/data

    ports:
      - "29317:29317"

    command: ["python3", "-m", "mautrix_telegram", "-c", "/data/config.yaml"]

